### ISSUE TITLE
Compile warnings etc. Can these be ignored?

### ISSUE THREAD

**Issue by Peppernrino** [derrod/lg4k-linux#3]
OS : Ubuntu Studio 20.04

I mean... it works... but I thought I'd still share a note of it in case something is off.

Any way I can optimize the compile?

> ******@******-*:~/lg4k-linux$ ./build.sh
make: Entering directory '/home/******/lg4k-linux/driver'
make -C /lib/modules/5.4.0-58-lowlatency/build M=/home/******/lg4k-linux/driver/ clean
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-58-lowlatency'
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-58-lowlatency'
make: Leaving directory '/home/******/lg4k-linux/driver'
make: Entering directory '/home/******/lg4k-linux/driver'
cp ../AverMediaLib_64.a AverMediaLib_64.o
make -C /lib/modules/5.4.0-58-lowlatency/build M=/home/******/lg4k-linux/driver/ modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-58-lowlatency'
  CC [M]  /home/******/lg4k-linux/driver//entry.o
  CC [M]  /home/******/lg4k-linux/driver//cxt_mgr.o
  CC [M]  /home/******/lg4k-linux/driver//utils/alsa/alsa_model.o
/home/******/lg4k-linux/driver//utils/alsa/alsa_model.c: In function ‘alsa_model_init’:
/home/******/lg4k-linux/driver//utils/alsa/alsa_model.c:622:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  622 |                 snd_card_free(card);
      |                 ^~~~~~~~~~~~~~~~~~~
/home/******/lg4k-linux/driver//utils/alsa/alsa_model.c:623:13: note: here
  623 |             case ALSA_MODEL_CREATE_SND_CARD_ERROR:
      |             ^~~~
  CC [M]  /home/******/lg4k-linux/driver//utils/gpio/gpio_model.o
  CC [M]  /home/******/lg4k-linux/driver//utils/i2c/i2c_model.o
/home/******/lg4k-linux/driver//utils/i2c/i2c_model.c: In function ‘i2c_model_bus_i2c_xfer’:
/home/******/lg4k-linux/driver//utils/i2c/i2c_model.c:107:5: warning: ISO C90 forbids variable length array ‘i2c_model_msg’ [-Wvla]
  107 |     i2c_model_msg_t i2c_model_msg[num];
      |     ^~~~~~~~~~~~~~~
/home/******/lg4k-linux/driver//utils/i2c/i2c_model.c: In function ‘i2c_model_transfer’:
/home/******/lg4k-linux/driver//utils/i2c/i2c_model.c:150:12: warning: ISO C90 forbids variable length array ‘msgs’ [-Wvla]
  150 |     struct i2c_msg msgs[num];
      |            ^~~~~~~
  CC [M]  /home/******/lg4k-linux/driver//utils/mem/mem_model.o
In file included from /home/******/lg4k-linux/driver/include/it6664_extern.h:16,
                 from /home/******/lg4k-linux/driver/include/ite6664.h:8,
                 from /home/******/lg4k-linux/driver/include/ite6805.h:11,
                 from /home/******/lg4k-linux/driver/include/aver_xilinx.h:21,
                 from /home/******/lg4k-linux/driver//utils/mem/mem_model.c:22:
/home/******/lg4k-linux/driver/include/it6664_IO.h:29:6: warning: "USING_1to8" is not defined, evaluates to 0 [-Wundef]
   29 | #if (USING_1to8==TRUE)
      |      ^~~~~~~~~~
  CC [M]  /home/******/lg4k-linux/driver//utils/misc/sys.o
  CC [M]  /home/******/lg4k-linux/driver//utils/misc/g_queue.o
  CC [M]  /home/******/lg4k-linux/driver//utils/pci/pci_model.o
/home/******/lg4k-linux/driver//utils/pci/pci_model.c: In function ‘pci_model_probe’:
/home/******/lg4k-linux/driver//utils/pci/pci_model.c:273:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  273 |                 pci_disable_device(pci_dev);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/******/lg4k-linux/driver//utils/pci/pci_model.c:274:13: note: here
  274 |             case ERROR_ENABLE_PCI_DEV:
      |             ^~~~
  CC [M]  /home/******/lg4k-linux/driver//utils/thread/task_model.o
  CC [M]  /home/******/lg4k-linux/driver//utils/trace/trace.o
/home/******/lg4k-linux/driver//utils/trace/trace.c: In function ‘trace_model_init’:
/home/******/lg4k-linux/driver//utils/trace/trace.c:348:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  348 |                 kobject_put(trace_cxt->kobj);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/******/lg4k-linux/driver//utils/trace/trace.c:349:13: note: here
  349 |             case ERR_NO_DEV_KOBJ:
      |             ^~~~
  CC [M]  /home/******/lg4k-linux/driver//utils/trace/debug.o
  CC [M]  /home/******/lg4k-linux/driver//utils/v4l2/v4l2_model_device.o
/home/******/lg4k-linux/driver//utils/v4l2/v4l2_model_device.c: In function ‘v4l2_model_init’:
/home/******/lg4k-linux/driver//utils/v4l2/v4l2_model_device.c:212:6: warning: this statement may fall through [-Wimplicit-fallthrough=]
  212 |      v4l2_model_vb2_release(context->vb2_context);
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/******/lg4k-linux/driver//utils/v4l2/v4l2_model_device.c:213:5: note: here
  213 |     case V4L2_MODEL_ERROR_VIDEO_BUF:
      |     ^~~~
/home/******/lg4k-linux/driver//utils/v4l2/v4l2_model_device.c:214:6: warning: this statement may fall through [-Wimplicit-fallthrough=]
  214 |      v4l2_device_unregister(&context->v4l2_dev);
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/******/lg4k-linux/driver//utils/v4l2/v4l2_model_device.c:215:5: note: here
  215 |     case V4L2_MODEL_ERROR_REGISTER_V4L2:
      |     ^~~~
  CC [M]  /home/******/lg4k-linux/driver//utils/v4l2/v4l2_model_ioctl.o
  CC [M]  /home/******/lg4k-linux/driver//utils/v4l2/v4l2_model_videobuf2.o
  CC [M]  /home/******/lg4k-linux/driver//utils/v4l2/v4l2_model_table.o
  CC [M]  /home/******/lg4k-linux/driver//utils/v4l2/framegrabber.o
  CC [M]  /home/******/lg4k-linux/driver//board/cx511h/board_config.o
In file included from /home/******/lg4k-linux/driver/include/it6664_extern.h:16,
                 from /home/******/lg4k-linux/driver/include/ite6664.h:8,
                 from /home/******/lg4k-linux/driver/include/ite6805.h:11,
                 from /home/******/lg4k-linux/driver/include/aver_xilinx.h:21,
                 from /home/******/lg4k-linux/driver//board/cx511h/board_config.c:24:
/home/******/lg4k-linux/driver/include/it6664_IO.h:29:6: warning: "USING_1to8" is not defined, evaluates to 0 [-Wundef]
   29 | #if (USING_1to8==TRUE)
      |      ^~~~~~~~~~
/home/******/lg4k-linux/driver//board/cx511h/board_config.c: In function ‘board_probe’:
/home/******/lg4k-linux/driver//board/cx511h/board_config.c:208:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  208 |                 cxt_manager_unref_context(i2c_mgr);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/******/lg4k-linux/driver//board/cx511h/board_config.c:209:13: note: here
  209 |             case ERROR_I2C_MGR:
      |             ^~~~
/home/******/lg4k-linux/driver//board/cx511h/board_config.c:210:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  210 |                 cxt_manager_unref_context(gpio_mgr);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/******/lg4k-linux/driver//board/cx511h/board_config.c:211:13: note: here
  211 |             case ERROR_GPIO_MGR:
      |             ^~~~
  CC [M]  /home/******/lg4k-linux/driver//board/cx511h/board_i2c.o
In file included from /home/******/lg4k-linux/driver/include/it6664_extern.h:16,
                 from /home/******/lg4k-linux/driver/include/ite6664.h:8,
                 from /home/******/lg4k-linux/driver/include/ite6805.h:11,
                 from /home/******/lg4k-linux/driver//board/cx511h/board_i2c.c:19:
/home/******/lg4k-linux/driver/include/it6664_IO.h:29:6: warning: "USING_1to8" is not defined, evaluates to 0 [-Wundef]
   29 | #if (USING_1to8==TRUE)
      |      ^~~~~~~~~~
  CC [M]  /home/******/lg4k-linux/driver//board/cx511h/board_gpio.o
In file included from /home/******/lg4k-linux/driver/include/it6664_extern.h:16,
                 from /home/******/lg4k-linux/driver/include/ite6664.h:8,
                 from /home/******/lg4k-linux/driver/include/ite6805.h:11,
                 from /home/******/lg4k-linux/driver/include/aver_xilinx.h:21,
                 from /home/******/lg4k-linux/driver//board/cx511h/board_gpio.c:18:
/home/******/lg4k-linux/driver/include/it6664_IO.h:29:6: warning: "USING_1to8" is not defined, evaluates to 0 [-Wundef]
   29 | #if (USING_1to8==TRUE)
      |      ^~~~~~~~~~
  CC [M]  /home/******/lg4k-linux/driver//board/cx511h/board_v4l2.o
In file included from /home/******/lg4k-linux/driver/include/it6664_extern.h:16,
                 from /home/******/lg4k-linux/driver/include/ite6664.h:8,
                 from /home/******/lg4k-linux/driver/include/ite6805.h:11,
                 from /home/******/lg4k-linux/driver/include/aver_xilinx.h:21,
                 from /home/******/lg4k-linux/driver//board/cx511h/board_v4l2.c:24:
/home/******/lg4k-linux/driver/include/it6664_IO.h:29:6: warning: "USING_1to8" is not defined, evaluates to 0 [-Wundef]
   29 | #if (USING_1to8==TRUE)
      |      ^~~~~~~~~~
/home/******/lg4k-linux/driver//board/cx511h/board_v4l2.c: In function ‘cx511h_stream_on’:
/home/******/lg4k-linux/driver//board/cx511h/board_v4l2.c:212:31: warning: unused variable ‘fe_audioinfo’ [-Wunused-variable]
  212 |     enum ite6805_audio_sample fe_audioinfo=0;
      |                               ^~~~~~~~~~~~
/home/******/lg4k-linux/driver//board/cx511h/board_v4l2.c: In function ‘cx511h_flash_dump’:
/home/******/lg4k-linux/driver//board/cx511h/board_v4l2.c:378:24: warning: unused variable ‘board_v4l2_cxt’ [-Wunused-variable]
  378 |  board_v4l2_context_t *board_v4l2_cxt=framegrabber_get_data(handle);
      |                        ^~~~~~~~~~~~~~
/home/******/lg4k-linux/driver//board/cx511h/board_v4l2.c: In function ‘cx511h_flash_update’:
/home/******/lg4k-linux/driver//board/cx511h/board_v4l2.c:389:24: warning: unused variable ‘board_v4l2_cxt’ [-Wunused-variable]
  389 |  board_v4l2_context_t *board_v4l2_cxt=framegrabber_get_data(handle);
      |                        ^~~~~~~~~~~~~~
  CC [M]  /home/******/lg4k-linux/driver//board/cx511h/board_alsa.o
In file included from /home/******/lg4k-linux/driver/include/it6664_extern.h:16,
                 from /home/******/lg4k-linux/driver/include/ite6664.h:8,
                 from /home/******/lg4k-linux/driver/include/ite6805.h:11,
                 from /home/******/lg4k-linux/driver/include/aver_xilinx.h:21,
                 from /home/******/lg4k-linux/driver//board/cx511h/board_alsa.c:22:
/home/******/lg4k-linux/driver/include/it6664_IO.h:29:6: warning: "USING_1to8" is not defined, evaluates to 0 [-Wundef]
   29 | #if (USING_1to8==TRUE)
      |      ^~~~~~~~~~
  LD [M]  /home/******/lg4k-linux/driver//cx511h.o
  Building modules, stage 2.
  MODPOST 1 modules
WARNING: could not find /home/******/lg4k-linux/driver//.AverMediaLib_64.o.cmd for /home/******/lg4k-linux/driver//AverMediaLib_64.o
  CC [M]  /home/******/lg4k-linux/driver//cx511h.mod.o
  LD [M]  /home/******/lg4k-linux/driver//cx511h.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-58-lowlatency'
make: Leaving directory '/home/******/lg4k-linux/driver'

**Comment by derrod** [comment]
Well warnings are just that; Warnings. Most of htese are just about unused variables or other minor things. You can simply ignore them.

**Comment by Peppernrino** [comment]
OK, thank you. I figured as much, but I felt it was important to leave here in case someone gets the same results and doesn't freak out.

And thank you for making this github project! I got my gf's computer streaming in 4K 60fps last night. I really appreciate your hard work. :)
