### ISSUE TITLE
Question about latency

### ISSUE THREAD

**Issue by peterlvilim** [derrod/lg4k-linux#5]
Hello!

Feel free to close this as this isn't a bug, but I figured you might be able to help me a bit before I do a bunch of digging.

I currently have 4 of these cards and am compositing them into one 8K image in OBS on Windows. I estimate that I'm seeing about 30-50 ms of lag when doing this. I'd like to try to reduce the lag of possible. I'm guessing there is a queue of frames somewhere in the system that is introducing the lag. At 60fps that's a frame every 16 ms, so I'm wondering if the lag is in processing on the hardware, in the driver, or in OBS. You happen to have any guesses? I was considering monkeying around with OBS and recompiling it some to try and see if there was latency inside OBS from some frame queue some place. I'm willing to accept some tearing, and right now it seems everything is vsynced.

**Comment by derrod** [comment]
I'm not familiar with the windows drivers or directshow, but I imagine 30-50 is as good as it's gonna get. Most capture devices require use of their own SDK to get very low latency by transferring the image data as it comes in. I assume DirectShow can't do that and always requires full frames, so depending on the amount of buffering happening on the card or driver, and how out of phase OBS and input refreshes are you're not going to get anyhting below that.
