### ISSUE TITLE
compilation error: conflicting types for ‘task_work_func_t’ (on Manjaro)

### ISSUE THREAD

**Issue by mozzieongit** [derrod/lg4k-linux#6]
Hi,
I get a compilation error when running make:
```
cp ../AverMediaLib_64.a AverMediaLib_64.o
make -C /lib/modules/5.10.23-1-MANJARO/build M=/home/<path-to-repo>/lg4k-linux/driver/ modules
make[1]: Entering directory '/usr/lib/modules/5.10.23-1-MANJARO/build'
  CC [M]  /home/<path-to-repo>/lg4k-linux/driver//utils/mem/mem_model.o
In file included from /home/<path-to-repo>/lg4k-linux/driver/include/ite6805.h:10,
                 from /home/<path-to-repo>/lg4k-linux/driver/include/aver_xilinx.h:21,
                 from /home/<path-to-repo>/lg4k-linux/driver//utils/mem/mem_model.c:22:
/home/<path-to-repo>/lg4k-linux/driver/utils/thread/include/task_model.h:27:20: error: conflicting types for ‘task_work_func_t’
   27 |     typedef void (*task_work_func_t)(void *data);
      |                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/posix-timers.h:9,
                 from ./include/linux/sched.h:33,
                 from ./include/linux/ratelimit.h:6,
                 from ./include/linux/dev_printk.h:16,
                 from ./include/linux/device.h:15,
                 from /home/<path-to-repo>/lg4k-linux/driver//utils/mem/mem_model.c:14:
./include/linux/task_work.h:8:16: note: previous declaration of ‘task_work_func_t’ was here
    8 | typedef void (*task_work_func_t)(struct callback_head *);
      |                ^~~~~~~~~~~~~~~~
In file included from /home/<path-to-repo>/lg4k-linux/driver/include/it6664_extern.h:16,
                 from /home/<path-to-repo>/lg4k-linux/driver/include/ite6664.h:8,
                 from /home/<path-to-repo>/lg4k-linux/driver/include/ite6805.h:11,
                 from /home/<path-to-repo>/lg4k-linux/driver/include/aver_xilinx.h:21,
                 from /home/<path-to-repo>/lg4k-linux/driver//utils/mem/mem_model.c:22:
/home/<path-to-repo>/lg4k-linux/driver/include/it6664_IO.h:29:6: warning: "USING_1to8" is not defined, evaluates to 0 [-Wundef]
   29 | #if (USING_1to8==TRUE)
      |      ^~~~~~~~~~
make[2]: *** [scripts/Makefile.build:279: /home/<path-to-repo>/lg4k-linux/driver//utils/mem/mem_model.o] Error 1
make[1]: *** [Makefile:1801: /home/<path-to-repo>/lg4k-linux/driver/] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.10.23-1-MANJARO/build'
make: *** [Makefile:60: build] Error 2
```

Is this a known issue? Do you have any suggestions how to fix this?

**Comment by cdorn0** [comment]
Linux Kernel developers introduced a symbol with the same name recently. If you change the symbol to another name (e.g. task_worker_func_t ) the module compiles

**Comment by mozzieongit** [comment]
Thanks. That works.
But... there is another kernel related error:
```
/home/<path-to-repo>/lg4k-linux/driver//utils/v4l2/v4l2_model_device.c: In function ‘v4l2_model_init’:
/home/<path-to-repo>/lg4k-linux/driver//utils/v4l2/v4l2_model_device.c:149:25: error: ‘VFL_TYPE_GRABBER’ undeclared (first use in this function); did you mean ‘VFL_TYPE_SUBDEV’?
  149 |            devicetype = VFL_TYPE_GRABBER;
      |                         ^~~~~~~~~~~~~~~~
      |                         VFL_TYPE_SUBDEV
```
this is related to a variable change it seems (see this [commit](https://github.com/torvalds/linux/commit/7fbbbc780eb30f0998234695ca7da15648af049b))
it compiles after change of `VFL_TYPE_GRABBER` to `VFL_TYPE_VIDEO`.
(btw, I'm working on the fedora branch as master throws many other errors)

does the line: `case DEVICE_TYPE_GRABBER:` also have to be changed? to `DEVICE_TYPE_VIDEO`? (I can't find anything with both names)

the next problem is make related:
`make[2]: *** [scripts/Makefile.modpost:111: /home/<path-to-repo>/lg4k-linux/driver//Module.symvers] Error 1`
lines of scripts/Makefile.modpost: 
```
(110) $(output-symdump): $(MODORDER) $(input-symdump) FORCE
(111)     $(call if_changed,modpost)
```

How do I change, where make searches for Module.symvers? (I found it in `/usr/lib/modules/5.10.23-1-MANJARO/build/Module.symvers` which should be the working directory as of `-C` specified in the make call, right?)

**Comment by cdorn0** [comment]
Changing VFL_TYPE_GRABBER to VFL_TYPE_VIDEO will get it to work. I pushed an updated master branch that builds with newer kernels in my repo, besides requiring to create an empty command file for the library.

**Comment by mozzieongit** [comment]
it works after creating the empty file `.AverMediaLib_64.o.cmd`
make clean removes this file. so just running ./build.sh doesn't work. 

for any future people interested (when cdorn0's PR gets merged): `cd driver && make clean && touch .AverMediaLib_64.o.cmd && make && cp cx511h.ko ../`

thank you a lot
